apiVersion: trutta.agents/v1
kind: Agent
name: repo-ingestion-agent
role: "Ingest and classify repository files into the ingestion index"

repository: "reis-ri6/Trutta_frames-A-c-"

inputs:
  - path: "./"      # read the full repo

outputs:
  - path: "ingestion/ingestion-index.yaml"
  - path: "ingestion/logs/"

capabilities:
  - file_read
  - file_write_limited
  - semantic_classification
  - similarity_search
  - summarisation

guardrails:
  - do_not_edit:
      - "docs/"
      - "concepts/"
      - "domains/"
      - "schemas/"
      - "templates/"
      - "agents/"
      - "infra/"
      - "progress/"
      - "monitoring/"
  - allowed_write:
      - "ingestion/ingestion-index.yaml"
      - "ingestion/logs/"
      - "**/*.clean.md"
      - "**/*.summary.md"

config:
  index_file: "ingestion/ingestion-index.yaml"
  log_dir: "ingestion/logs/"
  marketing_cleaning_spec: "ingestion/transforms/marketing-cleaning.md"
  code_classification_spec: "ingestion/transforms/code-classification.md"
