apiVersion: trutta.agents/v1
kind: System
name: doc-pipeline
type: data-conveyor

description: |
  Two-stage document pipeline:
  1) repo-ingestion-agent scans the repository and fills ingestion-index.
  2) doc-canonisation-agent promotes the best candidates into canonical artefacts.

stages:
  - name: ingestion
    agents:
      - repo-ingestion-agent

  - name: canonisation
    agents:
      - doc-canonisation-agent

schedule: "manual"    # can be triggered manually or by an external orchestrator
